runtime: python27
api_version: 1
threadsafe: true
default_expiration: "30d"

instance_class: F1
automatic_scaling:
  max_idle_instances: 1
  min_idle_instances: 1
  max_concurrent_requests: 20

libraries:
- name: ssl
  version: latest

inbound_services:
- warmup

includes:
- skip_files.yaml
- static_handlers.yaml

handlers:

- url: /_ah/warmup
  login: admin 
  script: wsgi.app

- url: /upload/.*
  script: upload.APP

- url: /.*
  script: wsgi.app
