name: pep257

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  pep257:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install pep257

    - name: source
      run: |
        python -m pep257 source

    - name: tests
      run: |
        python -m pep257 --match='.*\.py' tests/test
